[general]

import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[window]

decorations = "None"
opacity = 0.8

[scrolling]

history = 100000
multiplier = 3

[font]

normal = { family = "monospace", style = "Regular" }

[cursor]

style = { shape =  "Beam", blinking = "Always" }
blink_timeout = 0
unfocused_hollow = true

[terminal]

shell = { program = "/bin/fish"}

[mouse]

hide_when_typing = true

[keyboard]

#paste
#copy


